MERGE INTO GENRES(ID, NAME) KEY(ID) VALUES(1, 'Комедия');
MERGE INTO GENRES(ID, NAME) KEY(ID) VALUES(2, 'Драма');
MERGE INTO GENRES(ID, NAME) KEY(ID) VALUES(3, 'Мультфильм');
MERGE INTO GENRES(ID, NAME) KEY(ID) VALUES(4, 'Триллер');
MERGE INTO GENRES(ID, NAME) KEY(ID) VALUES(5, 'Документальный');
MERGE INTO GENRES(ID, NAME) KEY(ID) VALUES(6, 'Боевик');

MERGE INTO MPA(ID, NAME) KEY(ID) VALUES(1, 'G');
MERGE INTO MPA(ID, NAME) KEY(ID) VALUES(2, 'PG');
MERGE INTO MPA(ID, NAME) KEY(ID) VALUES(3, 'PG-13');
MERGE INTO MPA(ID, NAME) KEY(ID) VALUES(4, 'R');
MERGE INTO MPA(ID, NAME) KEY(ID) VALUES(5, 'NC-17');